### ISSUE TITLE
Write up todo list when upgrading

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidytemplate#64]
* [ ] Ensure using latest github action 
* [ ] Ensure Author includes RStudio as copyright holder and funder
* [ ] Update `DESCRIPTION`
* [ ] Ping Hadley to add plausible.io record
* [ ] Update template field
* [ ] Remove `strip_header: true`
* [ ] Remove algolia search, if used
* [ ] Eliminate superseded navbar customisation (`home: ~`, `news` instead of at top-level, article re-ordering)
* [ ] Remove any tidyverse author info
* [ ] Update `news` structure if needed
